use_frameworks!
platform :ios, ‘9.0’

target 'SwiftyBase_Example' do
  pod 'SwiftyBase', :path => '../'
 
  target 'SwiftyBase_Tests' do
    inherit! :search_paths

    pod 'Quick'
    pod 'Nimble'
  end
end
